.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:33+02:00  
.TH "ABORT" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ABORT \N'45' o anki hareketi geri alır   
.SH KULLANIM 
.nf
\fBABORT\fR [ \fBWORK\fR | \fBTRANSACTION\fR ]
.fi
    
.SH AÇIKLAMA
\fBABORT\fR o an geçerli olan hareketi geri sarar ve hareket tarafından gerçekleştirilen güncellemeleri iptal eder.  Bu komut bir standart SQL komutu olan \fBROLLBACK\fR [rollback(7)]\N'39'e eşdeğerdir ve sadece geçmişe uyumluluk adına vardır.   
  
.SH PARAMETRELER   
.br
.ns
.TP 
\fBWORK\fR, \fBTRANSACTION\fR
İsteğe bağlı anahtar sözcüklerdir. Bir etkileri yoktur.      

.PP  
.SH EK BİLGİ   
Bir hareketi başarıyla sonlandırmak için \fBCOMMIT\fR [commit(7)] kullanın.   

\fBABORT\fR, bir hareketin dışında kullanıldığında bir bozukluğa neden olmaz, sadece bir uyarı iletisinine sebep olur.   

.SH ÖRNEKLER
Tüm değişiklikleri geri almak için:    


.RS 4
.nf
ABORT;
.fi
.RE   

.SH UYUMLULUK
Bu komut bir PostgreSQL oluşumu olarak, geçmişe uyumluluk adına vardır. \fBROLLBACK\fR, standart SQL komut eşdeğeridir.   

.SH İLGİLİ BELGELER
\fBBEGIN\fR [begin(7)], \fBCOMMIT\fR [commit(7)], \fBROLLBACK\fR [rollback(7)].  

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Mart 2005 

  
