.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:34+02:00  
.TH "ALTER TYPE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ALTER TYPE \N'45' bir tür tanımını değiştirir   
.SH KULLANIM 
.nf
\fBALTER TYPE\fR \fIisim\fR \fBOWNER TO\fR \fIyeni_aidiyet\fR
.fi
    
.SH AÇIKLAMA
\fBALTER TYPE\fR mevcut bir türün tanımını değiştirir. Şimdilik yapabildiği tek şey bir türün sahibini değiştirmektir.   

.SH PARAMETRELER    
.br
.ns
.TP 
\fIisim\fR
Değiştirilecek mevcut bir türün ismi (şema nitelemeli olabilir).        

.TP 
\fIyeni_aidiyet\fR
Türün yeni sahibinin kullanıcı ismi. Bir türün sahibini değiştirebilmek için ayrıcalıklı kullanıcı olmalısınız.        

.PP    

.SH ÖRNEKLER
Kullanıcı tanımlı email türünün sahibini joe yapmak için:    


.RS 4
.nf
ALTER TYPE email OWNER TO joe;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBALTER TYPE\fR diye bir deyim yoktur.   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
   
