.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:33+02:00  
.TH "ALTER LANGUAGE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ALTER LANGUAGE \N'45' bir yordamsal dilin tanımını değiştirir   
.SH KULLANIM 
.nf

\fBALTER LANGUAGE\fR \fIisim\fR \fBRENAME TO\fR \fIyeni_isim\fR
.fi
    
.SH AÇIKLAMA
\fBALTER LANGUAGE\fR bir dilin tanımını değiştirir. Tek işlevselliği dilin ismini değiştirmektir. Bir dilin ismini sadece yarıcalıklı kullanıcı değiştirebilir.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Bir dilin ismi.      

.TP 
\fInewname\fR
Dilin yeni ismi.      

.PP  
.SH UYUMLULUK
SQL satandardında \fBALTER LANGUAGE\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBCREATE LANGUAGE\fR [create_language(7)], \fBDROP LANGUAGE\fR [drop_language(7)].  

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Mart 2005 
 
    
