.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:34+02:00  
.TH "ALTER OPERATOR CLASS" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ALTER OPERATOR CLASS \N'45' bir işleç sınıfının tanımını değiştirir   
.SH KULLANIM 
.nf
\fBALTER OPERATOR CLASS\fR \fIisim\fR \fBUSING\fR \fIindeksleme_yöntemi\fR \fBRENAME TO\fR \fIyeni_isim\fR
\fBALTER OPERATOR CLASS\fR \fIisim\fR \fBUSING\fR \fIindeksleme_yöntemi\fR \fBOWNER TO\fR \fIyeni_aidiyet\fR
.fi
    
.SH AÇIKLAMA
\fBALTER OPERATOR CLASS\fR bir işleç sınıfının tanımını değiştirir.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Mevcut bir işleç sınıfının ismi (şema nitelemeli olabilir).      

.TP 
\fIindeksleme_yöntemi\fR
Bu işleç sınıfının kullanıldığı indeksleme yönteminin ismi.      

.TP 
\fIyeni_isim\fR
İşleç sınıfının ismi.      

.TP 
\fIyeni_aidiyet\fR
İşleç sınıfının yeni sahibi. Bir işleç sınıfının sahibini değiştirmek için ayrıcalıklı kullanıcı olmalısınız.      

.PP  
.SH UYUMLULUK
SQL standardında \fBALTER OPERATOR CLASS\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBCREATE OPERATOR CLASS\fR [create_operator_class(7)]
.br
\fBDROP OPERATOR CLASS\fR [drop_operator_class(7)].  

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Mart 2005 
 
    
