.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:34+02:00  
.TH "ALTER TRIGGER" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ALTER TRIGGER \N'45' bir tetiğin tanımını değiştirir   
.SH KULLANIM 
.nf
\fBALTER TRIGGER\fR \fIisim\fR \fBON\fR \fItablo\fR \fBRENAME TO\fR \fIyeni_isim\fR
.fi
    
.SH AÇIKLAMA
\fBALTER TRIGGER\fR mevcut bir tetiğin özelliklerini değiştirir. RENAME deyimi tetiğin tanımına dokunmadan sadece ismin değiştirir.   

Özelliklerini değiştirebilmeniz için tetiğin etkilediği tablonun sahibi olmalısınız.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Değiştirilecek tetiğin ismi.      

.TP 
\fItablo\fR
Bu tetiğin etkildeği tablonun ismi.      

.TP 
\fIyeni_isim\fR
Tetiğin yeni ismi.      

.PP  
.SH ÖRNEKLER
Mevcut bir tetiğin ismini değiştirmek için:  


.RS 4
.nf
ALTER TRIGGER emp_stamp ON emp RENAME TO emp_track_chgs;
.fi
.RE   

.SH UYUMLULUK
\fBALTER TRIGGER\fR bir PostgreSQL oluşumudur.   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
