.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:33+02:00  
.TH "ALTER CONVERSION" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ALTER CONVERSION \N'45' bir dönüşümün tanımını değiştirir   
.SH KULLANIM 
.nf
\fBALTER CONVERSION\fR \fIisim\fR \fBRENAME TO\fR \fIyeni\N'45'isim\fR
\fBALTER CONVERSION\fR \fIisim\fR \fBOWNER TO\fR \fIyeni\N'45'aidiyet\fR
.fi
     
.SH AÇIKLAMA
\fBALTER CONVERSION\fR bir dönüşümün tanımını değiştirir.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Mevcut bir dönüşümün ismi (isteğe bağlı olarak şema nitelemeli).      

.TP 
\fIyeni\N'45'isim\fR
Dönüşümün yeni ismi.      

.TP 
\fIyeni\N'45'aidiyet\fR
Dönüşümün yeni aidiyeti Bir dönüşümün aidiyetini değiştirmek için ayrıcalıklı kullanıcı olmalısınız.      

.PP  
.SH ÖRNEKLER
iso_8859_1_to_utf_8 dönüşümünün ismini latin1_to_unicode yapmak için:    


.RS 4
.nf
ALTER CONVERSION iso_8859_1_to_utf_8 RENAME TO latin1_to_unicode;
.fi
.RE   

iso_8859_1_to_utf_8 dönüşümünün sahibini joe yapmak için:    


.RS 4
.nf
ALTER CONVERSION iso_8859_1_to_utf_8 OWNER TO joe;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBALTER CONVERSION\fR diye bir komut yoktur.   

.SH İLGİLİ BELGELER
\fBCREATE CONVERSION\fR [create_conversion(7)], \fBDROP CONVERSION\fR [drop_conversion(7)].  

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Mart 2005 
 
   
