.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:33+02:00  
.TH "ALTER AGGREGATE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ALTER AGGREGATE \N'45' bir ortak değer işlevinin tanımını değiştirir   
.SH KULLANIM 
.nf
\fBALTER AGGREGATE\fR \fIisim\fR ( \fItür\fR ) \fBRENAME TO\fR \fIyeni\N'45'isim\fR
\fBALTER AGGREGATE\fR \fIisim\fR ( \fItür\fR ) \fBOWNER TO\fR \fIyeni\N'45'aidiyet\fR
.fi
     
.SH AÇIKLAMA
\fBALTER AGGREGATE\fR bir ortak değer işlevinin tanımını değiştirir.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Mevcut bir ortak değer işlevinin ismi (isteğe bağlı olarak şema nitelemeli).      

.TP 
\fItür\fR
Ortak değer işlevinin argüman veri türü ya da işlev herhangi bir veri türünü kabul ediyorsa *      

.TP 
\fIyeni\N'45'isim\fR
Ortak değer işlevinin yeni ismi.      

.TP 
\fIyeni\N'45'aidiyet\fR
Ortak değer işlevinin yeni aidiyeti. Bir ortak değer işlevinin aidiyetini değiştirmk için ayrıcalıklı kullanıcı olmalısınız.      

.PP  
.SH ÖRNEKLER
integer türündeki myavg ortak değer işlevinin ismini my_average olarak değiştirmek için:    


.RS 4
.nf
ALTER AGGREGATE myavg(integer) RENAME TO my_average;
.fi
.RE   

integer türündeki myavg ortak değer işlevinin aidiyetini joe olarak değiştirmek için:    


.RS 4
.nf
ALTER AGGREGATE myavg(integer) OWNER TO joe;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBALTER AGGREGATE\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBCREATE AGGREGATE\fR [create_aggregate(7)], \fBDROP AGGREGATE\fR [drop_aggregate(7)].  

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Mart 2005 

   
