.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:34+02:00  
.TH "ALTER TABLESPACE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ALTER TABLESPACE \N'45' bir tablo alanının tanımını değiştirir   
.SH KULLANIM 
.nf
\fBALTER TABLESPACE\fR \fIisim\fR \fBRENAME TO\fR \fIyen_isim\fR
\fBALTER TABLESPACE\fR \fIisim\fR \fBOWNER TO\fR \fIyeni_aidiyet\fR
.fi
     
.SH AÇIKLAMA
\fBALTER TABLESPACE\fR bir tablo alanının tanımını değiştirir.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Mevcut bir tablo alanının ismi.      

.TP 
\fIyeni_isim\fR
Tablo alanını yeni ismi. Yeni isim, sistem tablo alanları için önek olarak ayrılmış olan pg_ dizgesiyle başlayamaz.      

.TP 
\fIyeni_aidiyet\fR
Tablo alanının yeni sahibi. Bir tablo alanının sahibini değiştirmek için ayrıcalıklı kullanıcı olmalısınız.      

.PP  
.SH ÖRNEKLER
index_space tablo alanının ismini fast_raid yapmak için:  


.RS 4
.nf
ALTER TABLESPACE index_space RENAME TO fast_raid;
.fi
.RE   

index_space tablo alanının sahibini değiştirmek için:   


.RS 4
.nf
ALTER TABLESPACE index_space OWNER TO mary;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBALTER TABLESPACE\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBCREATE TABLESPACE\fR [create_tablespace(7)], \fBDROP TABLESPACE\fR [drop_tablespace(7)].  

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Mart 2005 
 
    
