.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:34+02:00  
.TH "ALTER OPERATOR" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ALTER OPERATOR \N'45' bir işlecin tanımını değiştirir   
.SH KULLANIM 
.nf

\fBALTER OPERATOR\fR \fIname\fR ( { \fIsolterim_türü\fR | \fBNONE\fR },
\                      { \fIsağterim_türü\fR | \fBNONE\fR } ) \fBOWNER TO\fR \fIyeni_aidiyet\fR
.fi
    
.SH AÇIKLAMA
\fBALTER OPERATOR\fR bir işlecin tanımını değiştirir. Tek işlevselliği işlecin sahibini değiştirmektir.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Mevcut bir işlecin ismi (şema nitelemeli olabilir).      

.TP 
\fIsolterim_türü\fR
İşlecin sol tarafındaki teriminin veri türü. Böyle bir terim yoksa, NONE yazın.      

.TP 
\fIsağterim_türü\fR
İşlecin sağ tarafındaki teriminin veri türü. Böyle bir terim yoksa, NONE yazın.      

.TP 
\fIyeni_aidiyet\fR
İşlecin yeni sahibi. Bir işlecin sahibini sadece ayrıcalıklı kullanıcı değiştirebilir.      

.PP  
.SH ÖRNEKLER
Terimleri text türünde olan a @@ b özel işlecinin sahibini değiştirmek için:  


.RS 4
.nf
ALTER OPERATOR @@ (text, text) OWNER TO joe;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBALTER OPERATOR\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBCREATE OPERATOR\fR [create_operator(7)], \fBDROP OPERATOR\fR [drop_operator(7)].  

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Mart 2005 
 
    
