.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:34+02:00  
.TH "CREATE CONSTRAINT TRIGGER" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
CREATE CONSTRAINT TRIGGER \N'45' yeni bir kısıt tetiği tanımlar   
.SH KULLANIM 
.nf
\fBCREATE CONSTRAINT TRIGGER\fR \fIisim\fR
\    \fBAFTER\fR \fIolaylar\fR \fBON\fR
\    \fItablo_ismi\fR \fIkısıt\fR \fIöznitelikler\fR
\    \fBFOR EACH ROW EXECUTE PROCEDURE\fR \fIişlev_ismi\fR ( \fIargümanlar\fR )
.fi
    
.SH AÇIKLAMA
\fBCREATE CONSTRAINT TRIGGER\fR, \fBCREATE TABLE\fR/\fBALTER TABLE\fR içinde ve  \fBpg_dump\fR tarafından gösterimsel bütünlük için özel tetikler oluşturmakta kullanılır. Genel kullanım için tasarlanmamıştır.   

.SH PARAMETRELER     
.br
.ns
.TP 
\fIisim\fR
Kısıt tetiğinin ismi.       

.TP 
\fIolaylar\fR
Bu tetiği harekete geçirebilen olay kategorileri.       

.TP 
\fItablo_ismi\fR
Tetikleyen olanların oluştuğu tablonun ismi (şema nitelemeli olabilir).       

.TP 
\fIkısıt\fR
Asıl kısıt belirtimi.       

.TP 
\fIöznitelikler\fR
Kısıt öznitelikleri.       

.TP 
\fIişlev_ismi\fR(\fIargümanlar\fR)
Tetik işleminin parçası olarak çağrılacak işlev.       

.PP  
.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
