.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DEALLOCATE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DEALLOCATE \N'45' bir taslağı serbest bırakır   
.SH KULLANIM 
.nf
\fBDEALLOCATE\fR [ \fBPREPARE\fR ] \fItaslak_ismi\fR
.fi
    
.SH AÇIKLAMA
\fBDEALLOCATE\fR evvelce hazırlanmış bir SQL cümlesini serbest bırakmakta kullanılır. Bu yapılmadığı zaman, taslak oturum sonunda sistem tarafından serbest bırakılır.   

Taslaklar hakkında daha fazla bilgi için \fBPREPARE\fR [prepare(7)] kılavuz sayfasına bakınız.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fBPREPARE\fR
Yoksayılır.     

.TP 
\fItaslak_ismi\fR
Serbest bırakılacak taslağın ismi.     

.PP  
.SH UYUMLULUK
SQL standardı bir \fBDEALLOCATE\fR deyimi içerirse de, bu sadece gömülü SQL\N'39'de kullanmak içindir.   

.SH İLGİLİ BELGELER
\fBEXECUTE\fR [execute(7)], \fBPREPARE\fR [prepare(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
