.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP GROUP" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP GROUP \N'45' bir kullanıcı grubunu kaldırır   
.SH KULLANIM 
.nf
\fBDROP GROUP\fR \fIisim\fR
.fi
    
.SH AÇIKLAMA
\fBDROP GROUP\fR belirtilen grubu kaldırır. Gruptaki kullanıcılar kaldırılmaz.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Mevcut bir grubun ismi.     

.PP  
.SH EK BİLGİ
Nesneler üzerinde bazı yetkilere sahip bir grubu kaldırmak pek akıllıca olmaz. Şimdilik buna bakılmıyorsa da, ilerde bu bir hata olarak değerlendirilecektir.   

.SH ÖRNEKLER
Bir grubu kaldırmak için:   


.RS 4
.nf
DROP GROUP staff;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBDROP GROUP\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBALTER GROUP\fR [alter_group(7)], \fBCREATE GROUP\fR [create_group(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
