.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP SCHEMA" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP SCHEMA \N'45' bir şemayı kaldırır   
.SH KULLANIM 
.nf
\fBDROP SCHEMA\fR \fIisim\fR [, ...] [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMA
\fBDROP SCHEMA\fR veritabanınıdaki şemaları kaldırır.   

Bir şemayı sadece sahibi veya ayrıcalıklı kullanıcı kaldırabilir. Şemanın sahibi şema içindeki nesnelerin bazıları kendine ait olmasa bile şemayı ve dolayısıyla içindeki nesneleri veritabanından kaldırabilir.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Kaldırılacak şemanın ismi.     

.TP 
\fBCASCADE\fR
Şemaya bağımlı nesnelerin de (tablolar, işlevler, v.s.) silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
Şemaya bağımlı nesneler varsa şemanın kaldırılmasını engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER
Veritabanındaki mystuff şemasını içindekilerle beraber kaldırmak için:  


.RS 4
.nf
DROP SCHEMA mystuff CASCADE;
.fi
.RE   

.SH UYUMLULUK
SQL standardının bir defada sadece bir şema kaldırılmasına izin vermesi dışında, \fBDROP SCHEMA\fR SQL standardıyla tamamen uyumludur.   

.SH İLGİLİ BELGELER
\fBALTER SCHEMA\fR [alter_schema(7)], \fBCREATE SCHEMA\fR [create_schema(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
   
