.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP VIEW" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP VIEW \N'45' bir sanal tabloyu kaldırır   
.SH KULLANIM 
.nf
\fBDROP VIEW\fR \fIisim\fR [, ...] [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMA
\fBDROP VIEW\fR mevcut bir sanal tabloyu kaldırır.  Bu komutu çalıştırabilmek için sanal tablonun sahibi olmalısınız.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Kaldırılacak sanal tablonun ismi (şema nitelemeli olabilir).     

.TP 
\fBCASCADE\fR
Sanal tabloya bağımlı nesnelerin de (diğer sanal tablolar gibi) silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
Sanal tabloya bağımlı nesneler varsa, sanal tablonun kaldırılmasını engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER
kinds isimli sanal tabloyu kaldırmak için::   


.RS 4
.nf
DROP VIEW kinds;
.fi
.RE   

.SH UYUMLULUK
SQL standardının bir defada sadece bir sanal tablonun kaldırılmasına izin vermesi dışında, \fBDROP VIEW\fR SQL standardıyla tamamen uyumludur.   

.SH İLGİLİ BELGELER
\fBCREATE VIEW\fR [create_view(7)]   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
