.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP AGGREGATE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP AGGREGATE \N'45' bir ortak değer işlevini kaldırır   
.SH KULLANIM 
.nf
\fBDROP AGGREGATE\fR \fIisim\fR ( \fIveri_türü\fR ) [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMA
\fBDROP AGGREGATE\fR mevcut bir ortak değer işlevini silecektir. Komutu çalıştırabilmek için kullanıcının işlevin sahibi olması gerekir.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Silinecek ortak değer işlevinin ismi (şema nitelemeli olabilir).     

.TP 
\fIveri_türü\fR
Ortak değer işlevinin argüman veri türü. Eğer işlev her veri türünü kabul ediyorsa, * belirtilir.     

.TP 
CASCADE
Ortak değer işlevine bağımlı olan nesnelerin de silinmesini sağlar.     

.TP 
RESTRICT
Ortak değer işlevine bağımlı olan nesneler varsa işlevin silinmesini engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER
integer türünde argüman alan myavg isimli ortak değer işlevini silmek için:   


.RS 4
.nf
DROP AGGREGATE myavg(integer);
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBDROP AGGREGATE\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBALTER AGGREGATE\fR [alter_aggregate(7)],
.br
\fBCREATE AGGREGATE\fR [create_aggregate(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
