.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP TRIGGER" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP TRIGGER \N'45' bir tetik tanımını kaldırır   
.SH KULLANIM 
.nf
\fBDROP TRIGGER\fR \fIisim\fR \fBON\fR \fItablo\fR [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMALAR
\fBDROP TRIGGER\fR mevcut bir tetik tanımını kaldırır. Komutu çalıştırabilmek için, tetiğin tanımlandığı tablonun sahibi olmalısınız.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Kaldırılacak tetik tanımının ismi.     

.TP 
\fItablo\fR
Tetiğin tanımlandığı tablonun ismi (şema nitelemeli olabilir).     

.TP 
\fBCASCADE\fR
Tetiğe bağımlı nesnelerin de silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
Tetiğe bağımlı nesneler varsa tetiğin kaldırılmasını engeller. Bu öntanımlıdır.      

.PP  
.SH ÖRNEKLER   
films tablosundan if_dist_exists tetiğini kaldırmak için:   


.RS 4
.nf
DROP TRIGGER if_dist_exists ON films;
.fi
.RE   

.SH UYUMLULUK   
\fBDROP TRIGGER\fR deyimi SQL standardı ile uyumlu değildir. SQL standardında, tetik isimleri tablolara ait değildir, dolayısıyla komut tablo ismini içermez (\fBDROP TRIGGER \fR\fIisim\fR şeklinde kullanılır).   

.SH İLGİLİ BELGELER
\fBCREATE TRIGGER\fR [create_trigger(7)]   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
