.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP DOMAIN" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP DOMAIN \N'45' bir veri alanını kaldırır   
.SH KULLANIM 
.nf
\fBDROP DOMAIN\fR \fIisim\fR [, ...]  [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMA
\fBDROP DOMAIN\fR bir veri alanını kaldıracaktır.  Bir veri alanını silebilmek için sahibi olmalısınız.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Silinecek veri alanının ismi (şema nitelemeli olabilir).     

.TP 
\fBCASCADE\fR
Veri alanına bağımlı nesnelerin de (örn, tablo sütunları) silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
Veri alanına bağımlı nesneler varsa alanın silinmesini engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER
box isimli veri alanını kaldırmak için:  


.RS 4
.nf
DROP DOMAIN box;
.fi
.RE   

.SH UYUMLULUK   
Bu komut SQL standardıyla uyumludur.   

.SH İLGİLİ BELGELER   
\fBCREATE DOMAIN\fR [create_domain(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
   
