.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP CAST" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP CAST \N'45' bir tür dönüşümünü kaldırır   
.SH KULLANIM 
.nf
\fBDROP CAST\fR (\fIkaynak_tür\fR \fBAS\fR \fIhedef_tür\fR) [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMA
\fBDROP CAST\fR evvelce tanımlanmış bir tür dönüşümünü siler.   

Bir tür dönüşümünü silebilmek için, ya kaynak ya da hedef türün sahibi olmalısınız. Bunların, bir tür dönüşümünü tanımlamak için gereken izinlerle aynı olması gerekir.   

.SH PARAMETRELER    
.br
.ns
.TP 
\fIkaynak_tür\fR
Tür dönüşümünün kaynak veri türünün ismi.      

.TP 
\fIhedef_tür\fR
Tür dönüşümünün hedef veri türünün ismi.       

.TP 
\fBCASCADE\fR, \fBRESTRICT\fR
Tür dönüşümlerinde bir bağımlılık sözkonusu olmadığından bu sözcükler etkisizdir.      

.PP  
.SH ÖRNEKLER   
text türünden int türüne dönüşümü silmek için:   


.RS 4
.nf
DROP CAST (text AS int);
.fi
.RE   

.SH UYUMLULUK   
\fBDROP CAST\fR komutu SQL standardı ile uyumludur.   

.SH İLGİLİ BELGELER
\fBCREATE CAST\fR [create_cast(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
