.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP DATABASE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP DATABASE \N'45' bir veritabanını kaldırır   
.SH KULLANIM 
.nf
\fBDROP DATABASE\fR \fIisim\fR
.fi
    
.SH AÇIKLAMA
\fBDROP DATABASE\fR ismiyle belirtilen veritabanını kaldırır. Veritabanının katalog girdilerini kaldırdıktan sonra veriyi içeren dizini siler. Ancak, silinmesi istenen veritabanına siz ya da bir kullanıcı bağlı ise, komut yerine getirilemez. Bu bakımdan, bu komutu çalıştırabilmek için template1\N'39'e ya da başka bir veritabanına bağlanın.   

\fBDROP DATABASE\fR ile silinen bir veritabanı geri alınamaz. \fBDikkatli kullanın!\fR   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Silinecek veritabanının ismi.     

.PP  
.SH EK BİLGİ
\fBDROP DATABASE\fR bir hareket kümesinin içinden çalıştırılamaz.    

Bağlı olduğunuz veritabanını silemeyeceğinizden, işlemi komut satırından \fBdropdb(1)\fR ile yapmanız daha uygun olur; o da zaten bu komutu çalıştırır.   

.SH UYUMLULUK
SQL standardında \fBDROP DATABASE\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBCREATE DATABASE\fR [create_database(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
   
