.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP LANGUAGE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP LANGUAGE \N'45' bir yordamsal dili kaldırır   
.SH KULLANIM 
.nf
\fBDROP\fR [ \fBPROCEDURAL\fR ] \fBLANGUAGE\fR \fIisim\fR [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMA
\fBDROP LANGUAGE\fR, \fIisim\fR adlı evvelce kaydedilmiş yordamsal dilin tanımını siler.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Mevcut bir yordamsal dilin ismi. Geriye uyumlulk bakımından, isim tektırnakların içine alınmış olabilir.     

.TP 
\fBCASCADE\fR
Dile bağımlı nesnelerin de (örn, dilin işlevleri) silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
Dile bağımlı nesneler varsa dilin kaldırılmasını engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER
plsample yordamsal dilini kaldırmak için:  


.RS 4
.nf
DROP LANGUAGE plsample;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBDROP LANGUAGE\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBALTER LANGUAGE\fR [alter_language(7)],
.br
\fBCREATE LANGUAGE\fR [create_language(7)], \fBdroplang(1)\fR.   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
