.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP SEQUENCE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP SEQUENCE \N'45' bir kayıt listesi üretecini kaldırır   
.SH KULLANIM 
.nf
\fBDROP SEQUENCE\fR \fIisim\fR [, ...] [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMALAR
\fBDROP SEQUENCE\fR bir kayıt listesi üretecini kaldırır   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Kaldırılacak kayıt listesinin ismi (şema nitelemeli olabilir).     

.TP 
\fBCASCADE\fR
Kayıt listesine bağımlı nesnelerin de silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
Kayıt listesine bağımlı nesneler varsa kayıt listesinin kaldırılmasını engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER
serial isimli kayıt listesini silmek için:  


.RS 4
.nf
DROP SEQUENCE serial;
.fi
.RE   

.SH UYUMLULUK
SQL standardının bir defada sadece bir kayıt listesi kaldırılmasına izin vermesi dışında, \fBDROP SEQUENCE\fR SQL standardıyla tamamen uyumludur.   

.SH İLGİLİ BELGELER
\fBCREATE SEQUENCE\fR [create_sequence(7)]   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
