.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP FUNCTION" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP FUNCTION \N'45' bir işlevi kaldırır   
.SH KULLANIM 
.nf
\fBDROP FUNCTION\fR \fIisim\fR ( [ \fIveri_türü\fR [, ...] ] ) [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMA
\fBDROP FUNCTION\fR mevcut bir işlevin tanımını siler. Komutu çalıştırabilmek için işlevin sahibi olmalısınız. Farkı argümanları olan aynı isimde çok sayıda işlev olabileceğinden silinecek işlevin argümanlarını da belirtmelisiniz.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Mevcut bir işlevin ismi (şema nitelemeli olabilir).     

.TP 
\fIveri_türü\fR
İşlevin bir argümanının veri türü.     

.TP 
\fBCASCADE\fR
İşleve bağımlı nesnelerin de (örn, tetikler veya işleçler) silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
İşleve bağımlı nesneler varsa işlevin silinmesini engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER   
Karekök işlevini kaldırmak için:  


.RS 4
.nf
DROP FUNCTION sqrt(integer);
.fi
.RE   

.SH UYUMLULUK   
SQL standardında \fBDROP FUNCTION\fR diye bir deyim vardır ama bu komutla uyumlu değildir.   

.SH İLGİLİ BELGELER
\fBCREATE FUNCTION\fR [create_function(7)],
.br
\fBALTER FUNCTION\fR [alter_function(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
