.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP RULE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP RULE \N'45' bir yeniden yazma kuralını kaldırır   
.SH KULLANIM 
.nf
\fBDROP RULE\fR \fIisim\fR \fBON\fR \fItablo\fR [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMALAR
\fBDROP RULE\fR bir yeniden yazma kuralını kaldırır.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Kaldırılacak kuralın ismi.     

.TP 
\fItablo\fR
Kuralın uygulandığı tablo ya da sanal tablonun ismi (şema nitelemeli olabilir).     

.TP 
\fBCASCADE\fR
Kurala bağımlı nesnelerin de silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
Kurala bağımlı nesneler varsa kuralın kaldırılmasını engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER
newrule yeniden yazma kuralını kaldırmak için:  


.RS 4
.nf
DROP RULE newrule ON mytable;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBDROP RULE\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBCREATE RULE\fR [create_rule(7)]   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
