.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP TYPE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP TYPE \N'45' bir veri türünü kaldırır   
.SH KULLANIM 
.nf
\fBDROP TYPE\fR \fIisim\fR [, ...] [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMALAR
\fBDROP TYPE\fR kullanıcı tanımlı veri türlerini kaldırmak için kullanılır. Bir veri türünü kaldırmak için o veri türünün sahibi olmalısınız.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
Kaldırılacak veri türünün ismi (şema nitelemeli olabilir).     

.TP 
\fBCASCADE\fR
Veri türüne bağımlı nesnelerin de (tablo sütunları, işlevler, işleçler gibi) silinmesini sağlar.     

.TP 
\fBRESTRICT\fR
Veri türüne bağımlı nesneler varsa veri türünün kaldırılmasını engeller. Bu öntanımlıdır.     

.PP  
.SH ÖRNEKLER
box veri türünü kaldırmak için:   


.RS 4
.nf
DROP TYPE box;
.fi
.RE   

.SH UYUMLULUK   
\fBCREATE TYPE\fR SQL standardındaki adaşına benzemekle birlikte, komut ve veri türü eklenti mekanizması SQL standardındakinden farklıdır.   

.SH İLGİLİ BELGELER   
\fBCREATE TYPE\fR [create_type(7)], \fBALTER TYPE\fR [alter_type(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
