.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "DROP CONVERSION" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
DROP CONVERSION \N'45' bir karakter kümesi dönüşümünü kaldırır   
.SH KULLANIM 
.nf
\fBDROP CONVERSION\fR \fIisim\fR [ \fBCASCADE\fR | \fBRESTRICT\fR ]
.fi
    
.SH AÇIKLAMA
\fBDROP CONVERSION\fR evvelce tanımlanmış bir tür dönüşümünü kaldırır. Bir tür dönüşümünü kaldırabilmeniz için dönüşümün sahibi olmalısınız.   

.SH PARAMETRELER    
.br
.ns
.TP 
\fIname\fR
Tür dönüşümünün ismi (şema nitelemeli olabilir).      

.TP 
\fBCASCADE\fR, \fBRESTRICT\fR
Tür dönüşümlerinde bağımlılık sözkonusu olmadığından bu sözcükler etkisizdir.      

.PP  
.SH ÖRNEKLER
myname isimli dönüşümü silmek için:   


.RS 4
.nf
DROP CONVERSION myname;
.fi
.RE   

.SH UYUMLULUK   
SQL standardında \fBDROP CONVERSION\fR diye bir deyim yoktur.   

.SH SEE ALSO
\fBALTER CONVERSION\fR [alter_conversion(7)],
.br
\fBCREATE CONVERSION\fR [create_conversion(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
