.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:36+02:00  
.TH "END" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
END \N'45' o anki hareketi teslim eder   
.SH KULLANIM 
.nf
\fBEND\fR [ \fBWORK\fR | \fBTRANSACTION\fR ]
.fi
    
.SH AÇIKLAMALAR
\fBEND\fR o anki hareketi teslim eder. Hareket tarafından yapılan tüm değişiklikler diğerlerine görünür hale gelir ve bir çökme olsa bile değişikliklerin kalıcı olacağı garanti edilir. Bu komut, \fBCOMMIT\fR [commit(7)] komutuna eşdeğer bir PostgreSQL oluşumudur.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fBWORK\fR, \fBTRANSACTION\fR
Bir etkileri yoktur.     

.PP  
.SH EK BİLGİ
Bir hareketi iptal edip çıkmak için \fBROLLBACK\fR [rollback(7)]  kullanın.   

\fBEND\fR komutunun bir hareketin dışında kullanılması bir bozukluğa yol açmaz, ama bir uyarı iletisine sebep olur.   

.SH ÖRNEKLER
Bir hareketi teslim edip tüm değişiklikleri kalıcı yapmak için:   


.RS 4
.nf
END;
.fi
.RE   

.SH UYUMLULUK
\fBEND\fR komutu, SQL standardında belirtilen \fBCOMMIT\fR [commit(7)] komutuna eşdeğer bir PostgreSQL oluşumudur.   

.SH İLGİLİ BELGELER
\fBBEGIN\fR [begin(7)], \fBCOMMIT\fR [commit(7)], \fBROLLBACK\fR [rollback(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
