.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:37+02:00  
.TH "LOAD" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
LOAD \N'45' load or reload a shared library file   
.SH KULLANIM 
.nf
\fBLOAD\fR \N'39'\fIdosyaismi\fR\N'39'
.fi
    
.SH AÇIKLAMA
This command loads a shared library file into the PostgreSQL    server\N'39's address space.  If the file had been loaded previously,    it is first unloaded.  This command is primarily useful to unload    and reload a shared library file that has been changed since the    server first loaded it.  To make use of the shared library,    function(s) in it need to be declared using the \fBCREATE FUNCTION\fR [create_function(7)]    command.   

The file name is specified in the same way as for shared library    names in \fBCREATE FUNCTION\fR [create_function(7)]; in particular, one    may rely on a search path and automatic addition of the system\N'39's standard    shared library file name extension.  See "C\N'45'Language Functions" (http://www.postgresql.org/docs/8.0/static/xfunc\N'45'c.html) for    more information on this topic.   

.SH UYUMLULUK
\fBLOAD\fR bir PostgreSQL oluşumudur.   

.SH İLGİLİ BELGELER
\fBCREATE FUNCTION\fR [create_function(7)]   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
   
