.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:37+02:00  
.TH "MOVE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
MOVE \N'45' bir gösterici konumlandırır   
.SH KULLANIM 
.nf
\fBMOVE\fR [ \fIdirection\fR { \fBFROM\fR | \fBIN\fR } ] \fIgösterici_ismi\fR
.fi
     
.SH AÇIKLAMA
\fBMOVE\fR bir göstericiyi herhangi bir veri döndürmeden istenen konuna taşır. Göstericiyi belli bir konuma taşıyıp satır döndürmemesi dışında \fBFETCH\fR ile tamamen aynıdır.   

Sözdizimi ve kullanım ile ilgili ayrıntılar için \fBFETCH\fR [fetch(7)] kılavuz sayfasına bakınız.   
  
.SH ÇIKTILAR
Bir \fBMOVE\fR komutu işlemi başarıyla tamamlamışsa şöyle bir çıktı üretir:   


.RS 4
.nf
MOVE \fImiktar\fR
.fi
.RE   

\fImiktar\fR,  \fBFETCH\fR komutundaki gibi satır sayısını belirtir (sıfır olabilir).   

.SH ÖRNEKLER

.RS 4
.nf
BEGIN WORK;
DECLARE liahona CURSOR FOR SELECT * FROM films;

\N'45'\N'45' İlk 5 satırı atlayalım:
MOVE FORWARD 5 IN liahona;
MOVE 5

\N'45'\N'45' 6. satırı çekelim:
FETCH 1 FROM liahona;
code  | title  | did | date_prod  |  kind  |  len
\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'+\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'+\N'45'\N'45'\N'45'\N'45'\N'45'+\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'+\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'+\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'
P_303 | 48 Hrs | 103 | 1982\N'45'10\N'45'22 | Action | 01:37
(1 row)

\N'45'\N'45' Göstericiyi kapatıp hareketi sonlandıralım:
CLOSE liahona;
COMMIT WORK;
.fi
.RE
  
.SH UYUMLULUK
SQL standardında \fBMOVE\fR diye bir deyim yoktur.   

.SH İLGİLİ BELGELER
\fBCLOSE\fR [close(7)], \fBDECLARE\fR [declare(7)], \fBFETCH\fR [fetch(7)].  

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
   
