.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:37+02:00  
.TH "ROLLBACK" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
ROLLBACK \N'45' abort the current transaction   
.SH KULLANIM 
.nf
\fBROLLBACK\fR [ \fBWORK\fR | \fBTRANSACTION\fR ].fi
    
.SH AÇIKLAMA
\fBROLLBACK\fR rolls back the current transaction and causes    all the updates made by the transaction to be discarded.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fBWORK\fR, \fBTRANSACTION\fR
Optional key words. They have no effect.     

.PP  
.SH EK BİLGİ
Use \fBCOMMIT\fR [commit(7)] to    successfully terminate a transaction.   

Issuing \fBROLLBACK\fR when not inside a transaction does    no harm, but it will provoke a warning message.   

.SH ÖRNEKLER
To abort all changes:   


.RS 4
.nf
ROLLBACK;
.fi
.RE   

.SH UYUMLULUK
The SQL standard only specifies the two forms    \fBROLLBACK\fR and \fBROLLBACK    WORK\fR. Otherwise, this command is fully conforming.   

.SH İLGİLİ BELGELER
\fBBEGIN\fR [begin(7)], \fBCOMMIT\fR [commit(7)], \fBROLLBACK TO SAVEPOINT\fR [rollback_to(7)].   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
    
