.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:38+02:00  
.TH "TRUNCATE" 7 "" "PostgreSQL" "SQL \N'45' Dil Deyimleri"
.nh   
.SH İSİM
TRUNCATE \N'45' empty a table   
.SH KULLANIM 
.nf
\fBTRUNCATE\fR [ \fBTABLE\fR ] \fIisim\fR
.fi
    
.SH AÇIKLAMA
\fBTRUNCATE\fR quickly removes all rows from a    table. It has the same effect as an unqualified    \fBDELETE\fR but since it does not actually scan the    table it is faster. This is most useful on large tables.   

.SH PARAMETRELER   
.br
.ns
.TP 
\fIisim\fR
The name (optionally schema\N'45'qualified) of the table to be truncated.     

.PP  
.SH EK BİLGİ
\fBTRUNCATE\fR cannot be used if there are foreign\N'45'key references    to the table from other tables.  Checking validity in such cases would    require table scans, and the whole point is not to do one.   

\fBTRUNCATE\fR will not run any user\N'45'defined \fBON    DELETE\fR triggers that might exist for the table.   

.SH ÖRNEKLER
Truncate the table bigtable:   


.RS 4
.nf
TRUNCATE TABLE bigtable;
.fi
.RE   

.SH UYUMLULUK
SQL standardında \fBTRUNCATE\fR diye bir komut yoktur.   

.SH ÇEVİREN
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Nisan 2005 
 
   
