.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:24+02:00 
.\" Copyright (c) 1990, 1991, John W. Eaton. 
.\" 
.\" You may distribute under the terms of the GNU General Public 
.\" License as specified in the README file that comes with the man 1.0 
.\" distribution. 
.\" 
.\" John W. Eaton 
.\" jwe@che.utexas.edu 
.\" Department of Chemical Engineering 
.\" The University of Texas at Austin 
.\" Austin, Texas 78712   
.TH "apropos" 1 "15 Ocak 1991" "" ""
.nh    
.SH İSİM
apropos \N'45' whatis veritabanında anahtar sözcüğü arar    
.SH KULLANIM 
.nf
\fBapropos \fR\fIanahtar_kelime\fR...
.fi
      
.SH AÇIKLAMA
\fBapropos\fR, verilmiş \fIanahtar_kelime\fRler ışığında, sistem komutlarının kısa açıklamalarını içeren veri tabanlarında arama yapar ve sonuçları standart çıktıya yazar.     

.SH İLGİLİ BELGELER     
\fBman(1)\fR, \fBwhatis(1)\fR.     
   
.SH ÇEVİREN     
Yalçın Kolukısa <yalcin (at) belgeler.org>, Mart 2004
    
  
