.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:25+02:00   
.TH "bzdiff" 1 "" "" ""
.nh    
.SH İSİM
bzdiff \N'45' bzip2 ile sıkıştırılmış dosyaları karşılaştırır
.br
bzcmp \N'45' bzip2 ile sıkıştırılmış dosyaları karşılaştırır     
.SH KULLANIM 
.nf
\fBbzcmp\fR [ \fIcmp_seçenekleri\fR ] \fIdosya1\fR [ \fIdosya2\fR ]
\fBbzdiff\fR [ \fIdiff_seçenekleri\fR ] \fIdosya1\fR [ \fIdosya2\fR ]
.fi
   
.SH AÇIKLAMA
\fBbzcmp\fR  ve  \fBbzdiff\fR, \fBbzip2\fR ile sıkıştırılmış dosyalar üzerinde \fBcmp\fR ve \fBdiff\fR komutlarını çalıştırmak  için kullanılır. \fBcmp\fR ve \fBdiff\fR için geçerli olan bütün seçenekler burada da geçerlidir. Şayet tek bir dosya adı belirtilmişse, \fIdosya1\fR ve sıkıştırılmış \fIdosya1\fR.bz2 dosyalarını karşılaştırılır. Şayet iki dosya belirtilmişse, gerekli ise açılırlar ve \fBcmp\fR ya da \fBdiff\fR komutlarına gönderilirler. \fBcmp\fR veya \fBdiff\fR\N'39'ten dönen çıkış durumu korunur.     

.SH İLGİLİ BELGELER
\fBcmp(1)\fR, \fBdiff(1)\fR, \fBbzmore(1)\fR, \fBbzless(1)\fR, \fBbzgrep(1)\fR, \fBbzip2(1)\fR.     
   
.SH YETERSİZLİKLER     
\fBcmp\fR veya \fBdiff\fR komutlarından gelen iletiler belirtilen dosyalarla değil geçici dosyalarla ilgilidir.
   
.SH ÇEVİREN     
Yalçın Kolukısa <yalcin (at) belgeler.org>, Mart 2004
    
             
