.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:25+02:00   
.TH "bzgrep" 1 "" "" ""
.nh    
.SH İSİM
bzgrep \N'45' bir düzenli ifade için belirtilen bzip2 sıkıştırılmış dosyalarında grep ile arama yapar
.br
bzegrep \N'45' bir düzenli ifade için belirtilen bzip2 sıkıştırılmış dosyalarında egrep ile arama yapar
.br
bzfgrep \N'45' bir düzenli ifade için belirtilen bzip2 sıkıştırılmış dosyalarında fgrep ile arama yapar    
.SH KULLANIM 
.nf
\fBbzgrep\fR  [ \fIgrep_seçenekleri\fR ]   [ \fI\N'45'e\fR ] \fIifade dosya\fR ...
\fBbzegrep\fR [ \fIegrep_seçenekleri\fR ]  [ \fI\N'45'e\fR ] \fIifade dosya\fR ...
\fBbzfgrep\fR [ \fIfgrep_seçenekleri\fR ]  [ \fI\N'45'e\fR ] \fIifade dosya\fR ...
.fi
   
.SH AÇIKLAMA
\fBbzgrep\fR, \fBbzip2\fR ile sıkıştırılmış dosyalar üzerinde \fBgrep\fR çalıştırmak için kullanılır. \fBgrep\fR için geçerli olan bütün seçenekler burada da geçerlidir. Şayet \fIdosya\fR ismi belirtilmemişse, standart girdi, gerekli ise açıldıktan sonra \fBgrep\fR\N'39'e gönderilir. Eğer \fIdosya\fR ismi verilmişse, bu dosyalar gerekli ise açılır ve \fBgrep\fR\N'39'e gönderilir.     

Şayet \fBbzgrep\fR, \fBbzegrep\fR veya \fBbzfgrep\fR şeklinde çağrılır ise, \fBgrep\fR yerine \fBegrep\fR veya \fBfgrep\fR kullanılır. Eğer GREP ortam değişkeni ayarlanmışsa, \fBbzgrep\fR bu değişkeni \fBgrep\fR çağrısı olarak kullanır. Örneğin:     

\fBsh\fR için:  GREP=\fBfgrep  bzgrep \fR\fIifade dosyalar\fR
.br
\fBcsh\fR için: (\fBsetenv\fR GREP \fBfgrep\fR; \fBbzgrep \fR\fIifade dosyalar\fR)   

.SH YAZAN
Charles Levert <charles (at) comm.polymtl.ca> tarafından yazılmıştır.Debian GNU/Linux için \fBbzip2\fR\N'39'ye Philippe Troin <phil (at) fifi.org> tarafından uyarlanmıştır.   

.SH İLGİLİ BELGELER
\fBbzdiff(1)\fR, \fBbzmore(1)\fR, \fBbzmore(1)\fR, \fBbzip2(1)\fR, \fBgrep(1)\fR, \fBgrep(1)\fR, \fBgrep(1)\fR.     
   
.SH ÇEVİREN     
Yalçın Kolukısa <yalcin (at) belgeler.org>, Mart 2004
    
             
