.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:25+02:00   
.TH "chroot" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh    
.SH İSİM
chroot \N'45' özel kök dizini ile komut ya da etkileşimli kabuk çalıştırır    
.SH KULLANIM 
.nf
\fBchroot\fR [\fIyeni\N'45'kök\N'45'dizini\fR]  [\fIkomut\fR...]
\fBchroot\fR [\fIseçenek\fR]
.fi
       
.SH AÇIKLAMA     
Kök dizinini \fIyeni\N'45'kök\N'45'dizini\fR yaparak \fIkomut\fR\N'39'u çalıştırır.     


.br
.ns
.TP 
\fB\N'45'\N'45'help\fR
Bu yardım iletisini gösterir ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini gösterir ve çıkar.         

.PP     

Şayet bir \fIkomut\fR verilmez ise, \fB${SHELL} \N'45'i\fR çalıştırılır. (öntanımlı değer: /bin/sh)     
   
.SH YAZAN          
Roland McGrath tarafından yazılmıştır.
       
.SH GERİBİLDİRİM          
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.
       
.SH TELİF HAKKI          
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     
       
.SH İLGİLİ BELGELER          
\fBchroot(2)\fR     

\fBchroot\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBchroot\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils chroot\fR

.PP     
       
.SH ÇEVİREN          
Yalçın Kolukısa <yalcink01 (at) yahoo .com>, Kasım 2003
     
Kasım 2006\N'39'da güncellenmiştir.
    
   
