.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:26+02:00   
.TH "expand" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh   
.SH İSİM
expand \N'45' sekmeleri boşluklarla değiştirir   
.SH KULLANIM 
.nf
\fBexpand\fR [\fIseçenek\fR] ... [\fIdosya\fR] ...
.fi
      
.SH AÇIKLAMA
Her \fIdosya\fRnın içindeki sekmeleri boşluklarla değiştirip standart çıktıya basar. \fIdosya\fR verilmezse ya da \N'45' olarak verilirse standart girdi okunur.     

Uzun seçenekler için zorunlu olan argümanlar kısa seçenekler için de zorunludur.     

.br
.ns
.TP 
\fB\N'45'i\fR, \fB\N'45'\N'45'initial\fR
Boşluk oluşturmayan sekmeleri değiştirmez.         

.TP 
\fB\N'45't\fR, \fB\N'45'\N'45'tabs=\fR\fIsayı\fR
Sekmeler 8 değil \fIsayı\fR karakter olarak ele alınır.         

.TP 
\fB\N'45't\fR, \fB\N'45'\N'45'tabs=\fR\fIliste\fR
Sekme durakları için virgül ayraçlı \fIliste\fR kullanılır.         

.TP 
\fB\N'45'\N'45'help\fR
Yardım iletisini görüntüler ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini görüntüler ve çıkar.         

.PP     
   
.SH YAZAN     
David MacKenzie tarafından yazılmıştır.
   
.SH GERİBİLDİRİM     
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.
   
.SH TELİF HAKKI     
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     
   
.SH İLGİLİ BELGELER
\fBunexpand(1)\fR    

\fBexpand\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBexpand\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils expand\fR

.PP
   
.SH ÇEVİREN     
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Kasım 2006
    
  
