.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:27+02:00   
.TH "groups" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh   
.SH İSİM
groups \N'45' kullanıcının üyesi olduğu grupları basar   
.SH KULLANIM 
.nf
\fBgroups\fR [\fIseçenek\fR] ... [\fIkullanıcı\fR] ...
.fi
      
.SH AÇIKLAMA
Her \fIdosya\fRnın içindeki satırları (öntanımlı olarak standart girdiyi) katlar ve standart çıktıya basar.     

Uzun seçenekler için zorunlu olan argümanlar kısa seçenekler için de zorunludur.     

.br
.ns
.TP 
\fB\N'45'\N'45'help\fR
Yardım iletisini görüntüler ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini görüntüler ve çıkar.         

.PP     

\fBid \N'45'Gn\fR ile aynı. \fIkullanıcı\fR belirtilmezse o anki süreç kullanılır.
   
.SH YAZAN     
David MacKenzie tarafından yazılmıştır.
   
.SH GERİBİLDİRİM     
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.
   
.SH TELİF HAKKI     
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     
   
.SH İLGİLİ BELGELER
\fBgroups\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBgroups\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils groups\fR

.PP
   
.SH ÇEVİREN     
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Kasım 2006
    
  
