.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:27+02:00   
.TH "link" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh    
.SH İSİM
link \N'45' bir dosyaya bağ oluşturmak için link işlevini çağırır    
.SH KULLANIM 
.nf
\fBlink\fR \fIdosya1 dosya2\fR
\fBlink\fR \fIseçenek\fR
.fi
       
.SH AÇIKLAMA
Mevcut \fIdosya1\fRe \fIdosya2\fR bağını oluşturmak için link işlevini çağırır.     

.br
.ns
.TP 
\fB\N'45'\N'45'help\fR
Bu yardım iletisini gösterir ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini gösterir ve çıkar.         

.PP   
.SH YAZAN     
Michael Stone tarafından yazılmıştır.
   
.SH GERİBİLDİRİM     
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.     
   
.SH TELİF HAKKI     
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     
   
.SH İLGİLİ BELGELER
\fBunlink(1)\fR, \fBlink(2)\fR    

\fBlink\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBlink\fR yazılımları düzgün bir şekilde sisteminizde kuruluysa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils link\fR

.PP     
   
.SH ÇEVİREN     
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Kasım 2006
    
    
