.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:28+02:00   
.TH "mkfifo" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh   
.SH İSİM
mkfifo \N'45' FIFO\N'39'lar (isimli borular) oluşturur
.SH KULLANIM 
.nf
\fBmkfifo\fR [\fIseçenek\fR] \fIisim\fR ...
.fi
   
.SH AÇIKLAMA
\fIisim\fR ile belirtilen isimli borular (FIFO\N'39'lar) oluşturur.     

Uzun seçenekler için zorunlu olan argümanlar, kısa seçenekler için de zorunludur.     

.br
.ns
.TP 
\fB\N'45'm\fR, \fB\N'45'\N'45'mode=\fR\fIkip\fR
İzin kiplerini ayarlar (tıpkı \fBchmod\fR gibi) ama a=rw gibi ya da izin maskesi olarak değil.         

.TP 
\fB\N'45'\N'45'help\fR
Bu yardım metnini görüntüler ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini görüntüler ve çıkar.         

.PP     
   
.SH YAZAN     
David MacKenzie tarafından yazılmıştır.
   
.SH GERİBİLDİRİM     
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.
   
.SH TELİF HAKKI
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     

.SH İLGİLİ BELGELER
\fBmkfifo(3)\fR    

\fBmkfifo\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBmkfifo\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils mkfifo\fR

.PP     

.SH ÇEVİREN     
Yalçın Kolukısa <yalcink01 (at) yahoo .com>, Ağustos 2004

Kasım 2006\N'39'da güncellendi.
    
  
