.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:29+02:00   
.TH "pathchk" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh    
.SH İSİM
pathchk \N'45' dosya isimlerinin geçerliliğini ve taşınabilirliğini sınar    
.SH KULLANIM 
.nf
\fBpathchk \fR[\fIseçenek\fR] ... [\fIisim\fR] ...
.fi
      
.SH AÇIKLAMA   
\fIisim\fR içinde taşınabilir olmayan oluşumları teşhis eder.     

Uzun seçenekler için zorunlu olan argümanlar kısa seçenekler için de zorunludur.     


.br
.ns
.TP 
\fB\N'45'p\fR
Çoğu POSIX sistemi için sınar.         

.TP 
\fB\N'45'P\fR
Sınamayı boş isimler ve "\N'45'" ile başlayanlar için yapar.         

.TP 
\fB\N'45'\N'45'portability\fR
Sınamayı tüm POSIX sistemleri için yapar (\fB\N'45'p \N'45'P\fR ile aynı).         

.TP 
\fB\N'45'\N'45'help\fR
Bu yardım metnini basar ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini basar ve çıkar.         

.PP
    
.SH YAZAN
Paul Eggert, David MacKenzie ve Jim Meyering tarafından yazılmıştır.     

.SH GERİBİLDİRİM     
Bir yazılım hatası bulursanız, lütfen <bug\N'45'coreutils (at) gnu.org> adresine bildirin.     

.SH TELİF HAKKI
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     

.SH İLGİLİ BELGELER
\fBpathchk\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBpathchk\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils pathchk\fR

.PP     
   
.SH ÇEVİREN     
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Kasım 2006
    
   
