.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:29+02:00   
.TH "printenv" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh   
.SH İSİM
printenv \N'45' ortamı tamamen veya kısmen basar   
.SH KULLANIM 
.nf

\fBprintenv\fR [\fIdeğişken\fR] ...
\fBprintenv\fR  \fIseçenek\fR
.fi
      
.SH AÇIKLAMA
Hiç \fIdeğişken\fR belirtilmezse bütün ortam değişkenlerini basar.     

.br
.ns
.TP 
\fB\N'45'\N'45'help\fR
Yardım iletisini görüntüler ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini görüntüler ve çıkar.         

.PP     

.br
.ns
.TP 
\fBUyarı:\fR
Kullandığınız kabuk burada açıklanandan farklı bir \fBprintenv\fR komutu içeriyor olabilir. Desteklenen seçenekler için kullanmakta olduğunuz kabuğun belgelerine göz atmanız faydalı olabilir.     

.PP   
.SH YAZAN     
David MacKenzie ve Richard Mlynarik tarafından yazılmıştır.
   
.SH GERİBİLDİRİM     
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.
   
.SH TELİF HAKKI     
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     
   
.SH İLGİLİ BELGELER
\fBprintenv\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBprintenv\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils printenv\fR

.PP
   
.SH ÇEVİREN     
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Kasım 2006
    
  
