.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:31+02:00   
.TH "stty" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh   
.SH İSİM
stty \N'45' uçbirim hat ayarlarını basar ve değiştirir   
.SH KULLANIM 
.nf

\fBstty\fR [\fB\N'45'F\fR \fIaygıt\fR] [\fB\N'45'\N'45'file=\fR\fIaygıt\fR] [\fIayarlar\fR]
\fBstty\fR [\fB\N'45'F\fR \fIaygıt\fR] [\fB\N'45'\N'45'file=\fR\fIaygıt\fR] [\fB\N'45'a\fR|\fB\N'45'\N'45'all\fR]
\fBstty\fR [\fB\N'45'F\fR \fIaygıt\fR] [\fB\N'45'\N'45'file=\fR\fIaygıt\fR] [\fB\N'45'g\fR|\fB\N'45'\N'45'save\fR]
.fi
      
.SH AÇIKLAMA
Uçbirim karakteristiklerin basar ve değiştirir. 

Uzun seçenekler için zorunlu olan argümanlar kısa seçenekler için de zorunludur. 

.br
.ns
.TP 
\fB\N'45'a\fR, \fB\N'45'\N'45'all\fR
Tüm ayarları okunabilir biçimde gösterir.         

.TP 
\fB\N'45'g\fR, \fB\N'45'\N'45'save\fR
Tüm ayarları stty\N'45'okuyabilir biçimde gösterir         

.TP 
\fB\N'45'F\fR, \fB\N'45'\N'45'file=\fR\fIaygıt\fR
Standart girdi yerine belirtilen \fIaygıt\fRı açar ve kullanır.         

.TP 
\fB\N'45'\N'45'help\fR
Yardım iletisini görüntüler ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini görüntüler ve çıkar.         

.PP     
\fIayarlar\fRdan önceki seçimlik \N'96'\N'45'\N'39' anlamı ters çevirir. \fB*\fR karakteri POSIX olmayan ayarları gösterir. Hangi ayarların kullanılabileceği sisteme göre değişir.     

.SS Özel karakterler:    
.br
.ns
.TP 
* dsusp \fIkrkt\fR
\fIkrkt\fR okuma sırasında dur (SIGSTOP) sinyali gönderecektir.   

.TP 
eof \fIkrkt\fR
\fIkrkt\fR dosya sonu karakteri olacak  (girdiyi sonlandırır)   

.TP 
eol \fIkrkt\fR
\fIkrkt\fR satır sonu karakteri olacak   

.TP 
* eol2 \fIkrkt\fR
satır sonu için diğer bir \fIkrkt\fR olacaktır   

.TP 
erase \fIkrkt\fR
\fIkrkt\fR yazılan son karakteri silecektir   

.TP 
intr \fIkrkt\fR
\fIkrkt\fR bir kesme (SIGINT) sinyali gönderecektir   

.TP 
kill \fIkrkt\fR
\fIkrkt\fR bulunulan satırı silecektir   

.TP 
* lnext \fIkrkt\fR
\fIkrkt\fR izleyen özel karakterin yorumlanmasını engelleyecektir   

.TP 
quit \fIkrkt\fR
\fIkrkt\fR bir çıkış (SIGQUIT) sinyali gönderecektir   

.TP 
* rprnt \fIkrkt\fR
\fIkrkt\fR bulunulan satırı yeniden yazacaktır   

.TP 
start \fIkrkt\fR
\fIkrkt\fR durdurulduktan sonra çıktıyı yeniden başlatacaktır   

.TP 
stop \fIkrkt\fR
\fIkrkt\fR çıktıyı durduracaktır   

.TP 
susp \fIkrkt\fR
\fIkrkt\fR bir uçbirim dur (SIGSTOP) sinyali gönderecektir   

.TP 
* swtch \fIkrkt\fR
\fIkrkt\fR başka bir kabuk katmanına geçecektir   

.TP 
* werase \fIkrkt\fR
\fIkrkt\fR son sözcüğü silecektir   

.PP   
.SS Özel ayarlar: 
.nf
\  N             girdi/çıktı hızlarını N bit/s olarak ayarlar
* cols N        çekirdeğe uçbirimi N sütunluk olarak bildirir
* columns N     cols N ile aynı
\  ispeed N      girdi hızını N olarak ayarlar
* line N        hat disiplinini N yapar
\  min N         \N'45'icanon ile okumanın tamamlanması için gereken en az
\                karakter sayısını N yapar
\  ospeed N      çıktı hızını N olarak ayarlar
* rows N        çekirdeğe uçbirimi N satırlık olarak bildirir
* size          çekirdeğe uygun satır ve sütun sayısını gösterir
\  speed         hat hızını gösterir
\  time N        \N'45'icanon ile okuma zaman aşımını N/10 saniyeye ayarlar
.fi 
.SS Denetim ayarları: 
.nf
\  [\N'45']clocal     modem denetim sinyallerini geçersiz kılar
\  [\N'45']cread      girdi alımına izin verir
* [\N'45']crtscts    RTS/CTS uzlaşmasını etkinleştirir
\  csN           karakter bit sayısını N olarak ayarlar,
\                [N, 5..8 bit arasında]
\  [\N'45']cstopb     her karakter için iki durma biti kullanılır
\                (\N'96'\N'45'\N'39' ile bir)
\  [\N'45']hup        son işlem tty\N'39'yi kapatırken kapatma
\                (SIGHUP) sinyali gönderilir
\  [\N'45']hupcl      [\N'45']hup ile aynı
\  [\N'45']parenb     çıktı için eşlik biti üretilir,
\                girdi için eşlik biti beklenir
\  [\N'45']parodd     tek eşlik biti kullanılır (\N'96'\N'45'\N'39' ile çift)
.fi 
.SS Girdi ayarları: 
.nf
\  [\N'45']brkint     kırma karakterleri kesme sinyali üretir
\  [\N'45']icrnl      satırbaşı karakterini alt satıra geçme
\                karakteri olarak yorumlar
\  [\N'45']ignbrk     kırma karakterlerini yoksayar
\  [\N'45']igncr      satırbaşı karakterlerini yoksayar
\  [\N'45']ignpar     eşlik hataları olan karakterleri yoksayar
* [\N'45']imaxbel    girdi tamponu taştığında uyarı sesi üretir
\  [\N'45']inlcr      alt satıra geçme karakterini satırbaşı
\                karakteri olarak yorumlar
\  [\N'45']inpck      girdi eşlik denetimini etkinleştirir
\  [\N'45']istrip     girdi karakterlerinin yüksek (8.) bitini temizler
* [\N'45']iuclc      büyük harfleri küçük harf olarak yorumlar
* [\N'45']ixany      sadece başla karakteri değil herhangi bir karakter
\                girdiyi başlatır
\  [\N'45']ixoff      başla/dur karakterlerinin gönderimini etkinleştirir
\  [\N'45']ixon       XON/XOFF akış denetimini etkinleştirir
\  [\N'45']parmrk     eşlik hatalarını imler
\                (255\N'45'0\N'45'karakter sıralamasıyla)
\  [\N'45']tandem     [\N'45']ixoff ile aynı
.fi 
.SS Çıktı ayarları: 
.nf
* bsN           geri silme tarzı gecikme, N [0..1] arasında
* crN           satır başı tarzı gecikme, N [0..3] arasında
* ffN           sayfa başı tarzı gecikme, N [0..1] arasında
* nlN           alt satıra geçiş tarzı gecikme, N [0..1] arasında
* [\N'45']ocrnl      satır başını alt satıra geçiş olarak yorumlar
* [\N'45']ofdel      0 karakteri yerine dolgu için silme karakterini
\                kullanır
* [\N'45']ofill      gecikmeler için zamanlama yapmak yerine dolgu
\                karakterlerini kullanır
* [\N'45']olcuc      küçük harfleri büyük harf olarak yorumlar
* [\N'45']onlcr      alt satıra geçişi satır başı olarak yorumlar
* [\N'45']onlret     alt satıra geçiş karakteri satır başı yapar
* [\N'45']onocr      satır başı karakterini ilk karakter olarak basmaz
\  [\N'45']opost      işlem sonrası çıktı
* tabN          yatay sekme tarzı gecikme, N [0..3] arasında
* tabs          tab0 ile aynı
* \N'45'tabs         tab3 ile aynı
* vtN           düşey sekme tarzı gecikme, N [0..1] arasında
.fi 
.SS Yerel ayarlar: 
.nf
\  [\N'45']crterase   silme karakterlerini gerisilme\N'45'boşluk\N'45'gerisilme
\                olarak yansılar
* crtkill       satırları echoprt ve echoe ayarlarına
\                uygun olarak siler
* \N'45'crtkill      satırları echoctl ve echok ayarlarına
\                uygun olarak siler
* [\N'45']ctlecho    denetim karakterlerini şapkalı gösterim
\                (\N'96'^c\N'39') ile yansılar
\  [\N'45']echo       girdi karakterlerini yansılar
* [\N'45']echoctl    [\N'45']ctlecho ile aynı
\  [\N'45']echoe      [\N'45']crterase ile aynı
\  [\N'45']echok      karakteri sildikten sonra bir alt satıra
\                geçiş yansılar
* [\N'45']echoke     [\N'45']crtkill ile
\  [\N'45']echonl     diğer karakterler yansılanmamış olsa bile
\                alt satıra geçişi yansılar
* [\N'45']echoprt    geriye doğru silinmiş karakterleri \N'96'\\\N'39' ve \N'39'/\N'39'
\                arasında yansılar
\  [\N'45']icanon     karakter, satır, sözcük silmeleri ve satır
\                yenileme özel karakterlerini etkinleştirir
\  [\N'45']iexten     POSIX olmayan özel karakterleri etkinleştirir
\  [\N'45']isig       kesme, çıkış ve dondurma özel karakterlerini
\                etkinleştirir
\  [\N'45']noflsh     kesme ve çıkış özel karakterlerinden sonra
\                güncellemeyi geçersiz kılar
* [\N'45']prterase   [\N'45']echoprt ile aynı
* [\N'45']tostop     terminale yazmaya çalışan artalandaki işleri
\                durdurur
* [\N'45']xcase      icanon ile, büyük harfleri \N'96'\\\N'39' ile önceleyerek
\                gösterir
.fi 
.SS Birleşik ayarlar: 
.nf
* [\N'45']LCASE      [\N'45']lcase ile aynı
\  cbreak        \N'45'icanon ile aynı
\  \N'45'cbreak       icanon ile aynı
\  cooked        brkint ignpar istrip icrnl ixon opost isig
\                icanon eof ve eol karakterlerinin öntanımlı
\                değerleri ile aynı
\  \N'45'cooked       raw ile aynı
\  crt           echoe echoctl echoke ile aynı
\  dec           echoe echoctl echoke \N'45'ixany intr ^c erase 0177
\                kill ^u ile aynı
* [\N'45']decctlq    [\N'45']ixany ile aynı
\  ek            karakter ve satır silme karakterlerinin öntanımlı
\                değerleriyle aynı
\  evenp         parenb \N'45'parodd cs7 ile aynı
\  \N'45'evenp        \N'45'parenb cs8 ile aynı
* [\N'45']lcase      xcase iuclc olcuc ile aynı
\  litout        \N'45'parenb \N'45'istrip \N'45'opost cs8 ile aynı
\  \N'45'litout       parenb istrip opost cs7 ile aynı
\  nl            \N'45'icrnl \N'45'onlcr ile aynı
\  \N'45'nl           icrnl \N'45'inlcr \N'45'igncr onlcr \N'45'ocrnl \N'45'onlret ile aynı
\  oddp          parenb parodd cs7 ile aynı
\  \N'45'oddp         \N'45'parenb cs8 ile aynı
\  [\N'45']parity     [\N'45']evenp ile aynı
\  pass8         \N'45'parenb \N'45'istrip cs8 ile aynı
\  \N'45'pass8        parenb istrip cs7 ile aynı
\  raw           \N'45'ignbrk \N'45'brkint \N'45'ignpar \N'45'parmrk \N'45'inpck \N'45'istrip \N'45'inlcr
\                \N'45'igncr \N'45'icrnl  \N'45'ixon  \N'45'ixoff  \N'45'iuclc  \N'45'ixany \N'45'imaxbel
\                \N'45'opost \N'45'isig \N'45'icanon \N'45'xcase min 1 time 0 ile aynı
\  \N'45'raw          cooked ile aynı
\  sane          cread \N'45'ignbrk brkint \N'45'inlcr \N'45'igncr icrnl
\                \N'45'ixoff \N'45'iuclc \N'45'ixany imaxbel opost \N'45'olcuc \N'45'ocrnl onlcr
\                \N'45'onocr \N'45'onlret \N'45'ofill \N'45'ofdel nl0 cr0 tab0 bs0 vt0 ff0
\                isig icanon iexten echo echoe echok \N'45'echonl \N'45'noflsh
\                \N'45'xcase \N'45'tostop \N'45'echoprt echoctl echoke, tüm özel
\                karakterlerin öntanımlı değerleriyle aynı.
.fi
Standart girdiye bağlı olan tty hattını yönetir. Argümansız çalıştırıldığında iletişim hızını, hat disiplinini, stty sane ayarından farklı ayarları gösterir. Ayarlarda \fIkrkt\fR yazıldığı gibi ya da ^c, 0x37, 0177 ya da 127 olarak gösterilmiş bir karakter olabilir. ^\N'45' veya undef değerleri bu özel karakteri geçersiz kılar 
   
.SH YAZAN     
David MacKenzie tarafından yazılmıştır.
   
.SH GERİBİLDİRİM     
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.
   
.SH TELİF HAKKI     
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     
   
.SH İLGİLİ BELGELER
\fBstty\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBstty\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils stty\fR

.PP
   
.SH ÇEVİREN     
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Kasım 2006
    
  
