.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:31+02:00   
.TH "sum" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh   
.SH İSİM
sum \N'45' bir dosyadaki blok sayısını ve sağlama toplamını basar   
.SH KULLANIM 
.nf

\fBsum\fR [\fIseçenek\fR]... [\fIdosya\fR]...
.fi
      
.SH AÇIKLAMA
Her \fIdosya\fRnın sağlama toplamını ve blok sayısını yazar.     
.br
.ns
.TP 
\fB\N'45'r\fR
\fB\N'45's\fR seçeneğini iptal eder, BSD toplama algoritmasını kullanır, blok genişliğini 1K alır.         

.TP 
\fB\N'45's\fR, \fB\N'45'\N'45'sysv\fR
System V toplama algoritmasını kullanır, blok genişliğini 512 bayt alır         

.TP 
\fB\N'45'\N'45'help\fR
Yardım iletisini görüntüler ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini görüntüler ve çıkar.         

.PP     

\fIdosya\fR verilmemişse veya \N'45' verilmişse, standart girdi okunur.     
   
.SH YAZAN     
Kayvan Aghaiepour ve David MacKenzie tarafından yazılmıştır.
   
.SH GERİBİLDİRİM     
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.
   
.SH TELİF HAKKI     
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     
   
.SH İLGİLİ BELGELER
\fBsum\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBsum\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils sum\fR

.PP
   
.SH ÇEVİREN     
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Kasım 2006
    
  
