.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:31+02:00   
.TH "tty" 1 "Kasım 2006" "coreutils 6.5" "Kullanıcı Komutları"
.nh   
.SH İSİM
tty \N'45' standart girdiye bağlı terminalin dosya ismini basar   
.SH KULLANIM 
.nf
\fBtty\fR [\fIseçenek\fR]
.fi
      
.SH AÇIKLAMA
Standart girdiye bağlı terminalin dosya ismini gösterir. 
     
.br
.ns
.TP 
\fB\N'45's\fR, \fB\N'45'\N'45'silent\fR, \fB\N'45'\N'45'quiet\fR
Hiçbir şey basmaz, sadece bir çıkış durumu ile döner.         

.TP 
\fB\N'45'\N'45'help\fR
Yardım iletisini görüntüler ve çıkar.         

.TP 
\fB\N'45'\N'45'version\fR
Sürüm bilgilerini görüntüler ve çıkar.         

.PP         
.SH YAZAN    
David MacKenzie tarafından yazılmıştır.
   
.SH GERİBİLDİRİM     
Lütfen, böcekleri ve hataları <bug\N'45'coreutils (at) gnu.org> adresine bildirin.
   
.SH TELİF HAKKI     
Telif hakkı © 2006 Free Software Foundation, Inc.
.br
Bu bir özgür yazılımdır; GNU Genel Kamu Lisansının <http://www.gnu.org/licenses/gpl.html> koşullarına bağlı kalarak kopyalarını yeniden dağıtabilirsiniz. Yasaların izin verdiği ölçüde hiçbir garantisi yoktur; hatta SATILABİLİRLİĞİ veya ŞAHSİ KULLANIMINIZA UYGUNLUĞU için bile garanti verilmez.     
   
.SH İLGİLİ BELGELER
\fBtty\fR komutu ile ilgili kapsamlı bir kılavuz Texinfo olarak mevcuttur. Şayet \fBinfo\fR ve \fBtty\fR yazılımları düzgün bir şekilde sisteminizde mevcutsa, aşağıdaki komut ile bu kılavuzu görüntüleyebilirsiniz.     

.IP 

\fBinfo coreutils tty\fR

.PP
   
.SH ÇEVİREN     
Nilgün Belma Bugüner <nilgun (at) belgeler·gen·tr>, Kasım 2006
    
  
