.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:32+02:00  
.\"/* Copyright 1988,1990,1993,1994 by Paul Vixie 
.\" * All rights reserved 
.\" * 
.\" * Distribute freely, except: don\N'39't remove my name from the source or 
.\" * documentation (don\N'39't take credit for my work), mark your changes (don\N'39't 
.\" * get me blamed for your possible bugs), don\N'39't alter or remove this 
.\" * notice. May be sold if buildable source is provided to buyer. No 
.\" * warrantee of any kind, express or implied, is included with this 
.\" * software; use at your own risk, responsibility for damages (if any) to 
.\" * anyone resulting from the use of this software rests entirely with the 
.\" * user. 
.\" * 
.\" * Send bug reports, bug fixes, enhancements, requests, flames, etc., and 
.\" * I\N'39'll try to keep a version up to date. I can be reached as follows: 
.\" * Paul Vixie <paul@vix.com> uunet!decwrl!vixie!paul 
.\" */ 
.\"   
.TH "crontab" 5 "24 Ocak 1994" "4. Berkeley Dağıtımı" ""
.nh    
.SH İSİM
crontab \N'45' \fBcron\fR\N'39'u yöneten tablolar     
.SH AÇIKLAMA     
Bir crontab dosyasında, \fBcron(8)\fR sürecinin hangi zamanda hangi komutu çalıştıracağını belirten açıklamalar bulunur. Her kullanıcı kendi crontab dosyasına sahip olabilir. Bu kullanıcılara ait crontab dosyalarındaki zamanlanmış komutlar, crontab dosyasının sahibi hangi kullanıcı ise onun adı altında çalıştırılır.  Uucp ve  News genellikle kendi crontab dosyalarına sahiptirler, bu sayede bir \fBcron\fR komutunun parçası olarak \fBsu(1)\fR komutunu çalıştırma ihtiyacı ortadan kalkmış olur.     

Boş satırlar, sekmeler ve ara boşluklar yok sayılırlar. \N'96'#\N'39' karakteri ile başlayan satırlar yorum satırlarıdır. Dosyanın işletilmesi sırasında sistem tarafından önemsenmezler. Unutmayın ki, \fBcron\fR komutları ve yorumlar aynı satırda olamazlar. Bir yorum satırının devamında, bir \fBcron\fR komutu yer alıyorsa, sistem burasını da yorum olarak kabul eder ve işleme sokmaz.    Aynı şekilde; yorumlar da, ortam değişkeni ayarları biçiminde, aynı satırda yer alamazlar.     

Geçerli bir crontab satırı, ya ortam değişkenidir, ya da bir \fBcron\fR komutudur. Bir ortam değişkeni şu şekilde olur:     

.IP 

isim = değer

.PP     

Eşit işaretinin yanındaki boşluklar seçime bağlıdır. Değer içindeki sonraki boşluklar, isme atanan değerin bir parçası olarak kabul edileceklerdir. Değer dizgesi, önde veya arkada yer alan boşlukları korumak için,  çift ya da tek tırnak içinde olabilir. Buradaki temel nokta çift tırnak ile başlarsanız çift tırnak ile bitirmeniz gerektiğidir. Aynı şekilde tek tırnak ile başlarsanız tek tırnak ile bitirmelisiniz.     

Pek çok ortam değişkeni, \fBcron\fR(8) süreci tarafından düzenlenir. SHELL değişkeni, /bin/sh\N'39'ı işaret eder. LOGNAME ve HOME, crontab dosyasının sahibinin /etc/passwd dosyasındaki değerlerine göre ayarlanır.   HOME ve SHELL ortam değişkenleri, crontab içindeki ayrıca belirtilerek önemsenmeyebilir ama LOGNAME önemsenir.     

UYARI: BSD sistemlerde, LOGNAME değişkeni bazen USER olarak adlandırılabilir. Bu tür sistemlerde, USER değişkeni de ayarlanmalıdır.     

LOGNAME, HOME ve SHELL\N'39'e ek olarak; \fBcron(8)\fR, bu crontab dosyasındaki komutların çalışması sonucu e\N'45'posta göndermeyi gerektirecek bir durum ortaya çıkmışsa,  MAILTO değişkenini de arar. Şayet MAILTO  tanımlı ve içeriği boş değil ise, posta burada belirtilen kullanıcıya gönderilir. Şayet MAILTO belirtilmiş ama içeriği boş ise, (MAILTO="" gibi) e\N'45'posta gönderilmez. Diğer durumlarda, e\N'45'posta, crontab dosyasının sahibi olan kullanıcıya gönderilir.  Bu seçenek, \fBcron\fR\N'39'u yüklerken postacı olarak /usr/lib/sendmail  yerine /bin/mail kullanmaya karar verdiğiniz durumlarda oldukça faydalı olur \N'45'\N'45'  /bin/mail sahte isme izin vermez ve UUCP genellikle onun e\N'45'postalarını okumaz.     

Bir \fBcron\fR komutunun yapısı V7 standartı ile oldukça uyumludur. Her satır, sonunda bir komut olan,  beş adet zaman ve tarih alanına sahiptir. Şayet bu bir sistem crontab dosyası ise kullanıcı adı da belirtilir. Komutlar \fBcron(8)\fR tarafından işletilir. Burada belirtilen bir komutun işletilmesi için: dakika, saat ve ay bölümünün gerçek zaman ile aynı olması ve haftanın günü ya da ayın günü bölümününden en az birisinin gerçek zaman ile aynı olması gerekir (açıklama için aşağıdaki NOT\N'39'a bakınız).  Burada unutulmaması gereken bir nokta vardır: kayıp saatler diye adlandırabileceğimiz zaman (yaz saati, kış saati uygulamalarında geçişlerde yaşanan saat kaybı gibi) için ayarlanmış görevler asla çalışmayacaktır. Benzer şekilde, bir seferden daha fazla yaşanan saatler için ayarlanmış görevlerde iki kez çalıştırılacaktır (yaz saati kış saati değişimlerinde saatin geriye alınıp, iki kere aynı saat diliminin yaşanması).     

\fBcron(8)\fR, her dakika başı \fBcron\fR girişlerini gözden geçirir.     

Zaman ve tarih alanları:     


.nf
Alan adı            izin verilen değerler
\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'            \N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'\N'45'
minute                 0\N'45'59  (dakika)
hour                   0\N'45'23  (saat)
day of month           1\N'45'31  (ayın günü)
month                  1\N'45'12  (veya ay isimleri)
day of week            0\N'45'7   (Pazar günü için 0, 7; isim kullanılabilir.)
.fi     

Yıldız (*) ile işaretlenmiş bir alan baştan sona (=hepsi) anlamına gelir.     

Sayı aralıkları belirtilebilir. Aralıklar, \N'96'\N'45'\N'39' işareti ile ayrılmış iki sayıdan oluşur. Belirtilen bir aralığa başlangıç ve bitiş sayıları da dahildir.  Örneğin; 8\N'45'11 saat aralığı: 8,9,10 ve 11 saatlerini kapsar.     

Listeler kullanılabilir. Liste; virgül ile ayrılmış sayılar dizesidir. Örneğin: \N'96'\N'96'1,2,5,9\N'39'\N'39' ve \N'96'\N'96'0\N'45'4,8\N'45'12\N'39'\N'39'.     

Adım değerleri aralıklarla birlikte kullanılabilir. Bir aralıktan sonra \N'96'/<sayı>\N'39' şeklinde ifade edilir. Buradaki sayı adımlama değeridir. Örneğin; \N'34'0\N'45'23/2\N'34' saat ifadesi, V7 standartında \N'34'0,2,4,6,8,10,12,14,16,18,20,22\N'34' değerlerini ifade etmektedir. Adımlama bir yıldızdan \N'96'*\N'39'sonra da yapılabilir. \N'34'*/2\N'34' nin anlamı; her iki saatte bir demektir.     

\N'34'month\N'34' ve \N'34'day of week\N'34' alan adları için isimler de kullanılabilir. Büyük/küçük harf ayrımı olmaksızın ingilizce ismin ilk üç harfini kullanabilirsiniz. İsim aralıkları ve isim listelerini kullanamazsınız.     

6. alan (satırın geri kalanı kısmı) çalıştırılacak komutu belirtir. Satırsonu karakterine veya \N'34'%\N'34' işaretine kadar olan kısım, /bin/sh ya da \fBcrontab\fR\N'39'ın SHELL ortam değişkenince tanımlanmış olan kabuk tarafından çalıştırılır. Yüzde işareti \N'96'%\N'39', \N'96'\\\N'39' işareti ile öncelenmedikçe, satırsonu karakteri haline dönüşür ve ilk \N'96'%\N'39' den sonraki tüm bilgi, standart girdiye komut olarak gönderilir.     

Not \N'45' komutun çalıştırılacağı gün iki alandan ayarlanabilir: ayın günü ve haftanın günü. Her iki alanda belirli bir gün ile sınırlıysa (yani \N'96'*\N'39' değilse, yani belirtilmiş bir gün varsa), gerçek zaman bu iki değerden biri ile eşleşince, komut çalıştırılır. Örneğin; \N'96'\N'96'30 4 1,15 * 5\N'39'\N'39'  dizgesi bir komutu her ayın 1. ve 15. günleri saat 4:30\N'39'da, artı her Cuma çalıştırılır.     
   
.SH ÖRNEK CRON DOSYASI     

.nf
# komutları çalıştırmak için /bin/sh kullanılsın,
# /etc/passwd\N'39'de belirtilen önemsizdir
SHELL=/bin/sh
# kimin crontab\N'39'ı olduğunu boşver, bütün çıktıları \N'96'paul\N'39'e postala
MAILTO=paul
#
# hergün gece yarısından sonra beş dakika çalıştır
5 0 * * *       $HOME/bin/daily.job >> $HOME/tmp/out 2>&1
# her ayın ilk günü saat 14:15 de çalıştır \N'45'\N'45' çıktılar paul\N'39'e postalansın
15 14 1 * *     $HOME/bin/monthly
# hafta içi (Pazartesi\N'45'Cuma) hergün saat 22:00\N'39'da çalıştır ve Joe\N'39'yu kızdır
0 22 * * 1\N'45'5   mail \N'45's "Saat 22:00" joe%Joe,%%Çocukların nerede?%
23 0\N'45'23/2 * * * echo "her gün 00:23, 02:23, 04:23 de çalışır"
5 4 * * sun     echo "her Pazar 4:05\N'39'de çalışır"
.fi     
   
.SH İLGİLİ DOSYALAR     

.nf
/etc/crontab    Sistem crontab dosyası
.fi     
   
.SH İLGİLİ BELGELER     
\fBcron(8)\fR, \fBcrontab(1)\fR.     
   
.SH İLAVELER     
Haftanın günlerini belirtirken; hem 0. gün, hem de 7. gün Pazar olarak kabul edilecektir. BSD ve ATT bu konuda anlaşamamışlar gibi görünüyor.     

Listeler ve aralıklar aynı alan içinde birlikte olamazlar. \N'34'1\N'45'3,7\N'45'9" dizgesi ATT veya BSD \fBcron\fR\N'39'u tarafından reddedilecektir. \fBcron\fR komutu, bu dizge yerine \N'34'1\N'45'3\N'34' veya \N'34'7,8,9\N'34' şeklinde tanımlamaları kabul edecektir.     

Aralıklar adımlama içerebilir. "1\N'45'9/2" , "1,3,5,7,9" ile aynı anlamdadır.     

Ay ve haftanın günleri isim olarak belirtilebilir.     

Ortam değişkenleri crontab içinden ayarlanabilir. BSD  veya ATT\N'39'de alt süreçlere aktarılan ortam, /etc/rc içindekilerden birisidir.     

Komut çıktısı; crontab\N'39'ın sahibine postalanabilir (BSD bunu beceremez), crontab\N'39'ın sahibinden başkasına postalanabilir (SysV bunu beceremez) veya bu özellik kapatılabilir ve kimseye posta gönderilmez (SysV bunu da yapamaz).     
   
.SH YAZAN     
Paul Vixie <paul (at) vix.com> tarafından yazılmıştır.
   
.SH ÇEVİREN     
Yalçın Kolukısa <yalcink01 (at) yahoo.com>, Kasım 2003
    
   
