.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:38+02:00  
.\" Copyright 1992, 1993 Rickard E. Faith (faith@cs.unc.edu) 
.\" May be distributed under the GNU General Public License   
.TH "fdformat" 8 "1 Şubat 1993" "Linux 0.99" "Linux Yazılımcısının Lılavuzu"
.nh    
.SH İSİM
fdformat \N'45' bir diskete düşük seviyeli biçimleme uygular    
.SH KULLANIM 
.nf
\fBfdformat \fR[ \fB\N'45'n\fR ] \fIaygıt\fR
.fi
       
.SH AÇIKLAMA     
\fBfdformat\fR, bir diskete düşük seviyeli biçemleme uygular. Aygıt, genellikle aşağıdakilerden birisidir (disketler için, asıl aygıt numarası 2 [major=2] dir ve alt aygıt numaraları [minor] bilgilendirme amacı ile gösterilmektedir):     



.IP
.IP
.RS
.nf
/dev/fd0d360  (minor = 4)
/dev/fd0h1200 (minor = 8)
/dev/fd0D360  (minor = 12)
/dev/fd0H360  (minor = 12)
/dev/fd0D720  (minor = 16)
/dev/fd0H720  (minor = 16)
/dev/fd0h360  (minor = 20)
/dev/fd0h720  (minor = 24)
/dev/fd0H1440 (minor = 28)

/dev/fd1d360  (minor = 5)
/dev/fd1h1200 (minor = 9)
/dev/fd1D360  (minor = 13)
/dev/fd1H360  (minor = 13)
/dev/fd1D720  (minor = 17)
/dev/fd1H720  (minor = 17)
/dev/fd1h360  (minor = 21)
/dev/fd1h720  (minor = 25)
/dev/fd1H1440 (minor = 29)
.fi
.RE
.IP


.PP
Genel disket aygıtları, /dev/fd0 ve /dev/fd1 dir. Standart dışı bir biçim kullanıldığı veya biçim daha önceden özdevinimli olarak saptanamadığı zaman, \fBfdformat\fR hata verecektir. Bu durumda, disk parametrelerini yüklemek için \fBsetfdprm(8)\fR kullanın.     
   
.SH SEÇENEKLER     
.br
.ns
.TP 
\fB\N'45'n\fR
Doğrulama yapılmaz. Bu seçenek ile, biçimleme bittikten sonra yapılan doğrulama işlemi iptal edilmiş olur.       

.PP
   
.SH İLGİLİ BELGELER     
\fBfd(4)\fR, \fBemkfs(8)\fR, \fBmkfs(8)\fR, \fBsetfdprm(8)\fR.     
   
.SH YAZAN     
Werner Almesberger <almesber (at) nessie.cs.id.ethz.ch> tarafından yazılmıştır.     
   
.SH ÇEVİREN     
Yalçın Kolukısa <yalcink01 (at) yahoo.com>, Ocak 2004
    
   
