.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:39+02:00 
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu) 
.\" May be distributed under the GNU General Public License   
.TH "ipcs" 8 "9 Ekim 1993" "Linux 0.99" "Linux Yazılımcısının Kılavuzu"
.nh    
.SH İSİM
ipcs \N'45' süreçlerarası iletişim oluşumları hakkında bilgi verir    
.SH KULLANIM 
.nf
\fBipcs \fR[ \fB\N'45'asmq\fR ] [ \fB\N'45'tclup\fR ]
\fBipcs \fR[ \fB\N'45'smq\fR ] \fB\N'45'i \fR\fIkimlik\fR
\fBipcs \N'45'h\fR
.fi
       
.SH AÇIKLAMA     
IPC, InterProcess Communications (süreçlerarası iletişim) kısaltmasıdır.    

\fB\N'45'i\fR seçeneği belirli bir kimlik belirtilebilmesini sağlar. Sadece bu süreç kimliği hakkındaki bilgi görüntülenir.     

Özkaynaklar şöyle belirtilebilir:     

.br
.ns
.TP 
\fB\N'45'm\fR
Paylaşımlı bellek segmanları     

.TP 
\fB\N'45'q\fR
İleti kuyrukları     

.TP 
\fB\N'45's\fR
Semafor dizileri     

.TP 
\fB\N'45'a\fR
Hepsi (öntanımlı davranış)     

.PP

Çıktı biçimi aşağıdakilerden biri olarak tanımlanabilir:     

.br
.ns
.TP 
\fB\N'45't\fR
zaman     

.TP 
\fB\N'45'p\fR
süreç kimliği (PID)     

.TP 
\fB\N'45'c\fR
oluşturucu     

.TP 
\fB\N'45'l\fR
sınırlar     

.TP 
\fB\N'45'u\fR
özet     

.PP
   
.SH İLGİLİ BELGELER     
\fBipcrm(8)\fR     
  
.SH YAZAN     
Krishna Balasubramanian <balasub (at) cis.ohio\N'45'state.edu> tarafından yazılmıştır.     
   
.SH ÇEVİREN     
Yalçın Kolukısa <yalcink01 (at) yahoo.com>, Mart 2004
    
   
