.\" http://belgeler.org \N'45' 2006\N'45'11\N'45'26T10:18:40+02:00   
.TH "runlevel" 8 "27 Mayıs 1997" "" "Linux Sistem Yöneticisinin Kılavuzu"
.nh    
.SH İSİM
runlevel \N'45' geçerli ve bir önceki sistem çalışma seviyelerini bulur    
.SH KULLANIM 
.nf
\fBrunlevel\fR [\fIutmp\fR]
.fi
       
.SH AÇIKLAMA     
\fBrunlevel\fR çalışma seviyesi kayıtlarının tutulduğu, sistem \fIutmp\fR dosyasını okur (genellikle /var/run/utmp) ve standart çıktıya bir önceki çalışma seviyesini ve geçerli çalışma seviyesini yazar. Çalışma seviyeleri tek bir boşluk ile ayrılır. Şayet bir önceki çalışma seviyesi yok ise (çalışma seviyeleri hiç değişmemişse), bunun yerine \fBN\fR kullanılır.     

Eğer \fIutmp\fR dosyası yok ise veya herhangi bir kayıt bulunamazsa, \fBrunlevel\fR komutu \fBunknown\fR kelimesini ekrana yazar ve hata verip sonlanır.     

\fBrunlevel\fR, Sistem\N'45'V \fBwho \N'45'r\fR komutu yerine rc betikleri içinde kullanılabilir. Bununla birlikte, \fBinit(8)\fR\N'39'in yeni sürümlerinde, bu bilgi RUNLEVEL ve PREVLEVEL ortam değişkenlerinde mevcuttur.     
   
.SH SEÇENEKLER     
.br
.ns
.TP 
\fIutmp\fR
Okunacak \fIutmp\fR dosyasının ismi.

.PP
   
.SH İLGİLİ BELGELER     
\fButmp(5)\fR, \fBinit(8)\fR.     
  
.SH YAZAN     
Miquel van Smoorenburg, <miquels (at) cistron.nl> tarafından yazılmıştır.     
   
.SH ÇEVİREN     
Yalçın Kolukısa <yalcink01 (at) yahoo.com>, Aralık 2003
    
   
