#!/bin/bash

# bu betiği root çalıştırmalıdır.

MANDIR="/usr/share/man/tr";

# hem paket içinde hem de sistemde varolan dosyaları
# sistemden silelim.
cd tr

files=man?/*;
if [ "$files" != "man\?/\*" ]; then
  for i in $files;
  do
    rm -f $MANDIR/$i $MANDIR/$i.gz $MANDIR/$i.bz2;
  done;
fi

# paketi kuralım.
for i in man?; do
  install -d -m 755 $MANDIR/$i;
  install -m 644 $i/* $MANDIR/$i;
done;

cd -
# bitti
